# Generated by Django 5.2.7 on 2026-02-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.FloatField(default=1.55, help_text='Activity multiplier'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('lose', 'Lose'), ('maintain', 'Maintain'), ('gain', 'Gain')], default='maintain', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal_rate',
            field=models.FloatField(default=0.0, help_text='Fractional calorie change for goal (negative for loss)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
    ]
